import Head from "next/head";

const About = () => {
  return (
    <div>
      <Head>
        <title>next | about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>about</h1>
    </div>
  );
};

export default About;
