import Head from "next/head";

const Contact = () => {
  return (
    <div>
      <Head>
        <title>next | contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>contact</h1>
    </div>
  );
};

export default Contact;
